  
trigger:
- master

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      jobs:
      - job: Windows
        enableRichCodeNavigation: true
        richCodeNavigationEnvironment: 'production'
        pool:
          name: Hosted Windows 2019 with VS2019

        steps:
        - checkout: self
          clean: true

        # Build and rename binlog
        # The /p:Coverage argument is passed here since some build properties change to accommodate running with
        # coverage. This is part of the workarounds for https://github.com/tonerdo/coverlet/issues/362 and
        # https://github.com/tonerdo/coverlet/issues/363.
        - script: eng\cibuild.cmd
            -restore
            -build
            -configuration Debug
            /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\Debug\BuildSrc.binlog
          displayName: Build
        
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
            packageType: sdk
            version: 3.1.102
            installationPath: $(BUILD.SOURCESDIRECTORY)\.dotnet